// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCD5qxDDRrNOOErj9M3e1LRsHOUqWJ4cEw',
    appId: '1:125207472995:web:dc8aaab2f15639d9564156',
    messagingSenderId: '125207472995',
    projectId: 'flutter-training-efce7',
    authDomain: 'flutter-training-efce7.firebaseapp.com',
    storageBucket: 'flutter-training-efce7.appspot.com',
    measurementId: 'G-9R6B5D5XZS',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBpr9U-xUkxpa5cDyAi_UwfnyWPAQHtWPQ',
    appId: '1:125207472995:android:b98f0be3a43288fb564156',
    messagingSenderId: '125207472995',
    projectId: 'flutter-training-efce7',
    storageBucket: 'flutter-training-efce7.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBbndtTWT9OpEFUUUjejoWvqTQFtNf5xvM',
    appId: '1:125207472995:ios:af090694b5c9ff86564156',
    messagingSenderId: '125207472995',
    projectId: 'flutter-training-efce7',
    storageBucket: 'flutter-training-efce7.appspot.com',
    iosBundleId: 'com.example.training',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBbndtTWT9OpEFUUUjejoWvqTQFtNf5xvM',
    appId: '1:125207472995:ios:4bb518d5101b7e72564156',
    messagingSenderId: '125207472995',
    projectId: 'flutter-training-efce7',
    storageBucket: 'flutter-training-efce7.appspot.com',
    iosBundleId: 'com.example.training.RunnerTests',
  );
}
